openapi: 3.0.0
info:
  title: 'Line bot API'
  description: 'API for Line Bot'
  contact:
    name: 'Your Name'
    email: your-email@example.com
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000/api'
paths:
  /webhook:
    post:
      tags:
        - Webhook
      summary: '處理Line bot的webhook'
      operationId: 1edd6d23b8dd704d1bd7dc4328a8ea6f
      requestBody:
        description: 'Request data from Line'
        required: true
      responses:
        200:
          description: 'Successful operation'
          content:
            application/json:
              schema:
                properties:
                  message:
                    description: 'Response message'
                    type: string
                type: object
        500:
          description: 'Server error'
          content:
            application/json:
              schema:
                properties:
                  error:
                    description: 'Error message'
                    type: string
                type: object
